language: scala
scala:
   - 2.12.4

notifications:
    slack: initialcommitio:QadMr0XToU1nr1dteV5nYFpW

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y assembly

script:
 - mill brotli.assembly
