language: scala
scala:
   - 2.12.4

notifications:
    slack: initialcommitio:QadMr0XToU1nr1dteV5nYFpW

script:
 - sbt clean coverage test coverageReport

after_success:
  - bash <(curl -s https://codecov.io/bash)