language: scala
scala:
   - 2.12.4

notifications:
    slack: initialcommitio:QadMr0XToU1nr1dteV5nYFpW

before_install:
  - sudo curl -L -o ./mill
  - sudo chmod +x ./mill


script:
 - ./mill brotli.assembly
